### PR TITLE
Master

### PR DESCRIPTION
**Pull request by armantalk**
Made a box surface. Not sure how c++ objects work, so implemented hit function by getting an aabb through bounds() and invoking its hit function.

### CODE REVIEW

**Comment by andrew-pa** [comment]
looks OK, but you should calculate the AABB once in the constructor and then use it instead of recalculating it every intersection test, additionally returning it from bounds becomes simple

**Comment by andrew-pa** [comment]
Wait also you need to check some stuff: like that doesn't compile and you need to fill out the `hit_record` struct if it's nonnull, and additionally check to ensure that the intersection with the box is closer than the hit_record's existing intersection by comparing t values

**Comment by andrew-pa** [comment]
You're pretty close. You don't need the `center` or `extents` fields anymore b/c you have `bounds` instead; in addition you need to check to see if `hr` is `nullptr` (at which point it's either a hit or not and you don't need to fill out `hr`) also `hr` is a pointer

**Comment by andrew-pa** [comment]
one more thing: update it so that it calls `hit_record::set` instead of manually setting the fields

**Comment by armantalk** [comment]
Removing center/extends breaks get_normal() (it uses both). I need to go now, but when I get back I'll read up on what the normal point is and how to calculate it using the AABB.

**Comment by andrew-pa** [comment]
ok so like
1. calling a function on a pointer requires `->`
2. It's not python you need to have types when you declare variables, but also you can just basically eliminate any variables here except the position (which is correctly declared already) by passing their value directly into the function
3. You still need the `bounds` function, perhaps it might be good idea to rename the `bounds` field so that that can be there and not look confusing
4. You can calculate the center/extents of an AABB from the min/max rep, there is already a function that does that for the center in `aabb`, one for the extent would be fairly trivial and fix `get_normal`

**Pull request merged**
